services:
  app:
    container_name: site-${SITE_SLUG}
    build:
      context: ./current
      dockerfile: ../Dockerfile
      args:
        BUILD_COMMAND: ${BUILD_COMMAND:-npm run build}
    restart: unless-stopped
    networks:
      - hosting

networks:
  hosting:
    external: true
    name: someting_hosting
