services:
  app:
    container_name: site-${SITE_SLUG}
    build:
      context: ./current
      dockerfile: ../Dockerfile
    restart: unless-stopped
    networks:
      - hosting

networks:
  hosting:
    external: true
    name: someting_hosting
